dataset:
  batch_size: 128
  classes:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  dim:
  - 1
  - 10
  input_directory:
  - data/processed/subject-01
  - data/processed/subject-02
  - data/processed/subject-03
  - data/processed/subject-04
  - data/processed/subject-05
  - data/processed/subject-06
  - data/processed/subject-07
  - data/processed/subject-08
  - data/processed/subject-09
  - data/processed/subject-10
  - data/processed/subject-11
  - data/processed/subject-12
  - data/processed/subject-13
  - data/processed/subject-14
  - data/processed/subject-15
  - data/processed/subject-16
  - data/processed/subject-17
  - data/processed/subject-18
  - data/processed/subject-19
  - data/processed/subject-20
  - data/processed/subject-21
  - data/processed/subject-22
  - data/processed/subject-23
  - data/processed/subject-24
  - data/processed/subject-25
  - data/processed/subject-26
  - data/processed/subject-27
  mag_warping: 0.2
  min_max_norm: false
  noise_snr_db: 25
  pad_len: null
  pad_value: -10.0
  permutation: 0
  repetitions:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  rotation: 0
  rotation_mask: null
  sample_weight: true
  scale_sigma: 0.0
  shuffle: true
  size_factor: 10
  time_warping: 0.2
  update_after_epoch: false
  window_size: 0
  window_step: 0
model: {}
